---
- hosts: localhost
  gather_facts: no
  vars_files:
    - secret.yaml
  module_defaults:
    group/aws:
      region: "us-east-1"
  tasks:
    - name: RDS Private Group
      rds_subnet_group:
        name: module5-ig-private-dbgrp
        description: RDS group of private sub
        subnets:
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
        state: present
      register: private_dbgrp
    - name: Create RDS DB
      rds:
        command: create
        instance_name: module5-postgres-DB
        db_engine: postgres
        size: 20
        instance_type: db.t3.micro
        username: postgres
        password: "{{ password }}"
        subnet: module5-ig-private-dbgrp
        tags:
          Environment: testing
          Application: cms
        vpc_security_groups: "{{ postgres_sg.group_id }}"
