---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-east-1"
  tasks:
    - name: Create Auto Scaling Group
      ec2_asg:
        name: module5-ig-asg
        health_check_type: ELB
        wait_for_instances: False
        launch_template:
          launch_template_name: "module5-launch-template"
        min_size: 2
        max_size: 4
        desired_capacity: 2
        availability_zones:
          - "us-east-1a"
          - "us-east-1b"
        vpc_zone_identifier:
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
        target_group_arns: "{{ module5_ig_targetgroup.target_group_arn }}"
        state: present
