---
all:
  hosts:
    ec2-44-199-194-130.compute-1.amazonaws.com:
    ec2-18-213-113-147.compute-1.amazonaws.com:
    ec2-3-235-161-184.compute-1.amazonaws.com:
  children:
    al2:
      hosts:
        ec2-44-199-194-130.compute-1.amazonaws.com:
        ec2-18-213-113-147.compute-1.amazonaws.com:
      vars:
        ansible_user: ec2-user
        ansible_python_interpreter: /usr/bin/python
    ubuntu:
      hosts:
        ec2-3-235-161-184.compute-1.amazonaws.com:
      vars:
        ansible_user: ubuntu

